# mercure:
#     hubs:
#         default:
#             url: '%env(MERCURE_URL)%'
#             public_url: '%env(MERCURE_PUBLIC_URL)%'
#             jwt:
#                 secret: '%env(MERCURE_JWT_SECRET)%'
#                 publish: '*'
mercure:
  enable_profiler: '%kernel.debug%'
  hubs:
    default:
      url: '%env(MERCURE_PUBLISH_URL)%'
      jwt_provider: App\Services\Mercure\JwtProvider
