index:
   path: /
   controller: App\Controller\HomeController::index

# inscription:
#   path: /inscription
#   controller: App\Controller\InscriptionController::index

# security:
#   path: /login
#     controller: App\Controller\SecurityController::index