index:
   path: /
   controller: App\Controller\HomeController::index

# inscription:
#   path: /inscription
#   controller: App\Controller\InscriptionController::index

# connexion:
#   path: /connexion
#     controller: App\Controller\ConnexionController::index