# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { host: localhost, port: 9209 }
    indexes:
        app:
            types:
                brand:
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Brand
                        provider: ~
                        finder: ~
                    properties:
                        username: ~
                        name: ~
